version: '3.8'

services:
  frontend:
    build: 
      context: ./front_job
    ports:
      - "3000:3000"
    depends_on: 
      - backend
  backend:
    build:
      context: ./job
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    container_name: backend


     