# Generated by Django 3.2.7 on 2021-09-25 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotated', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='annotated',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
