# Generated by Django 3.2.7 on 2021-09-26 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotated', '0002_annotated_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='annotated',
            name='annotations',
            field=models.JSONField(null=True),
        ),
    ]
