# Generated by Django 3.2.7 on 2021-09-26 01:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('annotated', '0003_annotated_annotations'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='annotated',
            name='annotations',
        ),
    ]
