# Generated by Django 3.2.7 on 2021-09-26 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotated', '0004_remove_annotated_annotations'),
    ]

    operations = [
        migrations.AddField(
            model_name='annotated',
            name='annotations',
            field=models.JSONField(blank=True, default={'Label': '', 'Text': ''}),
        ),
    ]
